# Generated by Django 3.2.4 on 2022-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='ip',
        ),
        migrations.AddField(
            model_name='visit',
            name='today_num',
            field=models.IntegerField(default=0, verbose_name='今日访问量'),
        ),
        migrations.AddField(
            model_name='visit',
            name='total_num',
            field=models.IntegerField(default=0, verbose_name='今日访问量'),
        ),
    ]
