# Generated by Django 3.2.4 on 2022-03-01 16:06

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220301_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(null=True, verbose_name='内容'),
        ),
    ]
