# Generated by Django 4.0.2 on 2022-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avator',
            field=models.ImageField(null=True, upload_to='avator', verbose_name='头像'),
        ),
    ]
