# Generated by Django 4.0.2 on 2022-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_avator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avator',
        ),
        migrations.AddField(
            model_name='aboutauthor',
            name='avator',
            field=models.ImageField(null=True, upload_to='avator', verbose_name='头像'),
        ),
    ]
